#!/bin/bash   
# Author: Prashanth 
# Date Created: 21-03-2022
# Description: A simple command
# Date Modified:  21-03-2022 (2)
date | awk '{print $2, $3, $6, $1}'
echo "============================="
ls -la
echo "============================="
echo "Good Day!"
echo "============================="
