---
- name: install python-pip; install docker and run docker.py on managed nodes
  hosts: all
  tasks:
   - name: install python-pip
     apt:
      name: python3-pip
      state: present
      update_cache: yes
   - name: install docker and execute docker.py
     shell: "{{item}}"
     with_items:
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - pip install docker.py
...
