---
- name: install tomcat7 on all managed nodes
  hosts: all
  tasks:
   - name: install tomcat7
     apt: 
      name: tomcat7
      state: present
      update_cache: yes
   - name: install tomcat8
     apt: 
      name: tomcat8
      state: present
      update_cache: yes
   - name: create a file
     file:
      name: /home/ubuntu/file1.txt
      touch: file1
