---
- name: create a user and display the output
  hosts: all
  tasks:
   - name: create a user
     user:
      name: shiva
      password: 123456
     register: result
   - name: display the result
     debug: 
      var: result
...
